"use client";

export default function TermsPage() {
  return (
    <div style={{ fontFamily: "system-ui, sans-serif", color: "#111827" }}>
      <nav style={{ display: "flex", alignItems: "center", justifyContent: "space-between", padding: "16px 32px", borderBottom: "1px solid #e5e7eb", background: "#fff" }}>
        <a href="/" style={{ fontWeight: 800, fontSize: 20, color: "#111827", textDecoration: "none" }}>ForexAI Signals</a>
        <a href="/login" style={{ fontSize: 14, color: "#6b7280", textDecoration: "none" }}>Login</a>
      </nav>

      <div style={{ maxWidth: 720, margin: "0 auto", padding: "64px 24px" }}>
        <h1 style={{ fontSize: 36, fontWeight: 800, marginBottom: 8 }}>Terms and Conditions</h1>
        <p style={{ fontSize: 13, color: "#9ca3af", marginBottom: 40 }}>Last updated: January 2026</p>

        {[
          ["1. Acceptance of Terms", "By accessing or using ForexAI Signals, you agree to be bound by these Terms and Conditions. If you do not agree, please do not use this service."],
          ["2. Nature of Service", "ForexAI Signals provides automated technical analysis and informational content about forex markets. We do not provide personalised financial advice. Our signals are generated by algorithms and are for informational purposes only."],
          ["3. Risk Disclaimer", "Forex and CFD trading carries a high level of risk and may not be suitable for all investors. You may lose some or all of your invested capital. Past performance of signals does not guarantee future results. You should never trade with money you cannot afford to lose."],
          ["4. No Financial Advice", "Nothing on this platform constitutes financial, investment, legal, or tax advice. You should seek independent professional advice before making any trading decisions. We are not registered financial advisors."],
          ["5. Subscriptions and Payments", "Paid subscriptions are billed monthly or annually as selected. You may cancel at any time. Refunds are offered within 7 days of initial purchase. We reserve the right to change pricing with 30 days notice."],
          ["6. Account Responsibility", "You are responsible for maintaining the confidentiality of your account credentials. You are responsible for all activity that occurs under your account."],
          ["7. Limitation of Liability", "ForexAI Signals shall not be liable for any trading losses, loss of profits, or any other direct, indirect, or consequential damages arising from use of our service or reliance on our signals."],
          ["8. Intellectual Property", "All content, algorithms, and materials on this platform are the intellectual property of ForexAI Signals and may not be reproduced without written permission."],
          ["9. Termination", "We reserve the right to suspend or terminate your account at any time for violation of these terms or for any other reason at our discretion."],
          ["10. Governing Law", "These terms are governed by the laws of England and Wales. Any disputes shall be subject to the exclusive jurisdiction of the courts of England and Wales."],
          ["11. Contact", "For questions about these terms, contact us at: legal@signals.abokifx.app"],
        ].map(([title, content]) => (
          <div key={title} style={{ marginBottom: 32 }}>
            <h2 style={{ fontSize: 17, fontWeight: 700, marginBottom: 8 }}>{title}</h2>
            <p style={{ fontSize: 15, color: "#374151", lineHeight: 1.8, margin: 0 }}>{content}</p>
          </div>
        ))}
      </div>

      <footer style={{ borderTop: "1px solid #e5e7eb", padding: "24px", textAlign: "center" }}>
        <div style={{ display: "flex", gap: 24, justifyContent: "center", flexWrap: "wrap" }}>
          <a href="/privacy" style={{ fontSize: 13, color: "#6b7280", textDecoration: "none" }}>Privacy Policy</a>
          <a href="/contact" style={{ fontSize: 13, color: "#6b7280", textDecoration: "none" }}>Contact</a>
          <a href="/" style={{ fontSize: 13, color: "#6b7280", textDecoration: "none" }}>Home</a>
        </div>
      </footer>
    </div>
  );
}
